trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Node10:
      node.version: 10.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"
    workingDirectory: '$(Build.SourcesDirectory)/Lab2'

  - task: CopyFiles@2
    displayName: "Copy package.json file"
    inputs:
      sourceFolder: "$(System.DefaultWorkingDirectory)"
      contents: "package.json"
      targetFolder: "$(Build.ArtifactStagingDirectory)"
      cleanTargetFolder: true

  - task: CopyFiles@2
    displayName: "Copy built files"
    inputs:
      sourceFolder: "Lab2/dist"
      contents: "**"
      targetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish artifact"
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: "drop"   
